### ISSUE TITLE
Segmentation fault when trying to run RASPA2 with examples from gRASPA

### ISSUE THREAD

**Issue by NightXBurn** [snurr-group/gRASPA#57]
I'm trying to run some examples from gRASPA repo using RASPA2. Every time I run the simulate command I got Segmentation fault (core dumped). Is there a blueprint that I should follow when converting simulations from RASPA2 to gRASPA.

To reproduce:
1- Install RASPA2 following the instructions from https://github.com/iRASPA/RASPA2
2- Clone the https://github.com/snurr-group/gRASPA repo
3- Get in the directory of an example from gRASPA/Examples
4- Run RASPA2 with the simulate command

Thank you for the great work

![Screen Shot 2024-10-25 at 00 03 24](https://github.com/user-attachments/assets/7ad15634-4d37-4334-9ea3-13ecebdd21d4)

**Comment by KaihangShi** [comment]
Hi, gRASPA and RASPA2 are two independent software packages, although they share some similar input formats and conventions. If you want to try gRASPA examples, you should install the gRASPA package instead of RASPA2. Installation instructions for gRASPA are available in the [user manual](https://zhaoli2042.github.io/gRASPA-mkdoc/Installation.html).

**Comment by Zhaoli2042** [comment]
Hi, There are some differences between input commands of RASPA2 and gRASPA, although they look very similar. 
As Kaihang mentioned, please refer to the user manual of gRASPA/RASPA2 for more instructions. 
In terms of the files, the **definition** files (molecule definition, force field definition) could be used by both codes, while for the **simulation.input** file, gRASPA has some modified keywords and RASPA2 may not recognize them. 
Hope it helps!

**Comment by KASSARhahaha** [comment]
Hi, Prof. Zhao, I wanna ask whether you could provide high-throughput computing codes ?

**Comment by KASSARhahaha** [comment]
Dear Prof.Zhao,I feel really grateful for your kind help!!!Best regards,杨凯On Dec 12, 2024, at 00:07, Zhao Li ***@***.***> wrote:﻿

Hi, Prof. Zhao, I wanna ask whether you could provide high-throughput computing codes ?

Hi, it is in the releases: https://github.com/snurr-group/gRASPA/releases/tag/v-htc. Please email me ***@***.***) if you have any questions!
