### ISSUE TITLE
Regarding gRASPA-fast version

### ISSUE THREAD

**Issue by gokhanonderaksu** [snurr-group/gRASPA#58]
Hello,

First of all, thanks for this simulation software, as it is gonna help me a lot for especially computationally demanding simulations.

I wanted to have a look at gRASPA and gRASPA-fast simulations. Comparing examples given in the packages released, only difference I saw is that "UseMaxStep yes" in the gRASPA-fast. I saw other parameters regarding Widom, and Gibbs, but since I am only interested in GCMC simulations, I didn't think they are related to. 

So my questions are;
(i) Is there any other difference that I should be careful about? 
(ii) If there is, should there be any other additional github packages that I need to compile for using gRASPA-fast?

Thanks for your response in advance!

**Comment by Zhaoli2042** [comment]
Hi, 
Thanks for your interest. gRASPA-fast (available in the releases [here](https://github.com/snurr-group/gRASPA/releases/tag/v_fast_0.0.1)) is slightly (about 20%) faster than gRASPA.
1. the "fast" one can only do single-component GCMC (not mixtures); it outputs only the total energies but not the decomposed energies (framework-framework, framework-adsorbate, adsorbate-adsorbate). The supported features are listed in the table in [readme](https://github.com/snurr-group/gRASPA/blob/main/README.md#table-of-code-capabilities).
2. Compilation is almost the same; there should be a compilation file in the release; you just need to execute it. You need an [NVHPC compiler](https://developer.nvidia.com/hpc-sdk-downloads)

**Comment by gokhanonderaksu** [comment]
Thank you so much for your quick response! All the best!
